namespace cafeManagement
{
    partial class ControlForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ControlForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.accountButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.statisticButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.hoaDonBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.orderBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.menuButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.overviewBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.displayFormPanel = new System.Windows.Forms.Panel();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.panel1.Controls.Add(this.bunifuSeparator2);
            this.panel1.Controls.Add(this.bunifuSeparator1);
            this.panel1.Controls.Add(this.bunifuButton3);
            this.panel1.Controls.Add(this.accountButton);
            this.panel1.Controls.Add(this.statisticButton);
            this.panel1.Controls.Add(this.hoaDonBtn);
            this.panel1.Controls.Add(this.orderBtn);
            this.panel1.Controls.Add(this.menuButton);
            this.panel1.Controls.Add(this.overviewBtn);
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(255, 704);
            this.panel1.TabIndex = 0;
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.DoubleEdgeFaded;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(0, 76);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(267, 16);
            this.bunifuSeparator2.TabIndex = 4;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.DoubleEdgeFaded;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(-3, 535);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(267, 16);
            this.bunifuSeparator1.TabIndex = 4;
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton3.ButtonText = "Đăng xuất";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges1;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.bunifuButton3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.bunifuButton3.IdleBorderRadius = 1;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(0, 659);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 1;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 1;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.bunifuButton3.OnIdleState.BorderRadius = 1;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 1;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(259, 45);
            this.bunifuButton3.TabIndex = 3;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.signOut_click);
            // 
            // accountButton
            // 
            this.accountButton.AllowAnimations = true;
            this.accountButton.AllowMouseEffects = true;
            this.accountButton.AllowToggling = false;
            this.accountButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.accountButton.AnimationSpeed = 200;
            this.accountButton.AutoGenerateColors = false;
            this.accountButton.AutoRoundBorders = false;
            this.accountButton.AutoSizeLeftIcon = true;
            this.accountButton.AutoSizeRightIcon = true;
            this.accountButton.BackColor = System.Drawing.Color.Transparent;
            this.accountButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.accountButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("accountButton.BackgroundImage")));
            this.accountButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.accountButton.ButtonText = "Tài khoản";
            this.accountButton.ButtonTextMarginLeft = 0;
            this.accountButton.ColorContrastOnClick = 45;
            this.accountButton.ColorContrastOnHover = 45;
            this.accountButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.accountButton.CustomizableEdges = borderEdges2;
            this.accountButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.accountButton.DisabledBorderColor = System.Drawing.Color.Black;
            this.accountButton.DisabledFillColor = System.Drawing.Color.Black;
            this.accountButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.accountButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.accountButton.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.accountButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.accountButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.accountButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.accountButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.accountButton.IconMarginLeft = 11;
            this.accountButton.IconPadding = 10;
            this.accountButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.accountButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.accountButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.accountButton.IconSize = 25;
            this.accountButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.accountButton.IdleBorderRadius = 1;
            this.accountButton.IdleBorderThickness = 1;
            this.accountButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.accountButton.IdleIconLeftImage = null;
            this.accountButton.IdleIconRightImage = null;
            this.accountButton.IndicateFocus = false;
            this.accountButton.Location = new System.Drawing.Point(0, 608);
            this.accountButton.Name = "accountButton";
            this.accountButton.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.accountButton.OnDisabledState.BorderRadius = 1;
            this.accountButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.accountButton.OnDisabledState.BorderThickness = 1;
            this.accountButton.OnDisabledState.FillColor = System.Drawing.Color.Black;
            this.accountButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.accountButton.OnDisabledState.IconLeftImage = null;
            this.accountButton.OnDisabledState.IconRightImage = null;
            this.accountButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(123)))), ((int)(((byte)(104)))));
            this.accountButton.onHoverState.BorderRadius = 1;
            this.accountButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.accountButton.onHoverState.BorderThickness = 1;
            this.accountButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(123)))), ((int)(((byte)(104)))));
            this.accountButton.onHoverState.ForeColor = System.Drawing.SystemColors.Info;
            this.accountButton.onHoverState.IconLeftImage = null;
            this.accountButton.onHoverState.IconRightImage = null;
            this.accountButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.accountButton.OnIdleState.BorderRadius = 1;
            this.accountButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.accountButton.OnIdleState.BorderThickness = 1;
            this.accountButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.accountButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.accountButton.OnIdleState.IconLeftImage = null;
            this.accountButton.OnIdleState.IconRightImage = null;
            this.accountButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.accountButton.OnPressedState.BorderRadius = 1;
            this.accountButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.accountButton.OnPressedState.BorderThickness = 1;
            this.accountButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.accountButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.accountButton.OnPressedState.IconLeftImage = null;
            this.accountButton.OnPressedState.IconRightImage = null;
            this.accountButton.Size = new System.Drawing.Size(256, 45);
            this.accountButton.TabIndex = 3;
            this.accountButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.accountButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.accountButton.TextMarginLeft = 0;
            this.accountButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.accountButton.UseDefaultRadiusAndThickness = true;
            this.accountButton.Click += new System.EventHandler(this.AccountButton_Click);
            // 
            // statisticButton
            // 
            this.statisticButton.AllowAnimations = true;
            this.statisticButton.AllowMouseEffects = true;
            this.statisticButton.AllowToggling = false;
            this.statisticButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.statisticButton.AnimationSpeed = 200;
            this.statisticButton.AutoGenerateColors = false;
            this.statisticButton.AutoRoundBorders = false;
            this.statisticButton.AutoSizeLeftIcon = true;
            this.statisticButton.AutoSizeRightIcon = true;
            this.statisticButton.BackColor = System.Drawing.Color.Transparent;
            this.statisticButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.statisticButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("statisticButton.BackgroundImage")));
            this.statisticButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.statisticButton.ButtonText = "Thống kê";
            this.statisticButton.ButtonTextMarginLeft = 0;
            this.statisticButton.ColorContrastOnClick = 45;
            this.statisticButton.ColorContrastOnHover = 45;
            this.statisticButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.statisticButton.CustomizableEdges = borderEdges3;
            this.statisticButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.statisticButton.DisabledBorderColor = System.Drawing.Color.Black;
            this.statisticButton.DisabledFillColor = System.Drawing.Color.Black;
            this.statisticButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.statisticButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.statisticButton.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.statisticButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.statisticButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.statisticButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.statisticButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.statisticButton.IconMarginLeft = 11;
            this.statisticButton.IconPadding = 10;
            this.statisticButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.statisticButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.statisticButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.statisticButton.IconSize = 25;
            this.statisticButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.statisticButton.IdleBorderRadius = 1;
            this.statisticButton.IdleBorderThickness = 1;
            this.statisticButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.statisticButton.IdleIconLeftImage = null;
            this.statisticButton.IdleIconRightImage = null;
            this.statisticButton.IndicateFocus = false;
            this.statisticButton.Location = new System.Drawing.Point(0, 557);
            this.statisticButton.Name = "statisticButton";
            this.statisticButton.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.statisticButton.OnDisabledState.BorderRadius = 1;
            this.statisticButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.statisticButton.OnDisabledState.BorderThickness = 1;
            this.statisticButton.OnDisabledState.FillColor = System.Drawing.Color.Black;
            this.statisticButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.statisticButton.OnDisabledState.IconLeftImage = null;
            this.statisticButton.OnDisabledState.IconRightImage = null;
            this.statisticButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.statisticButton.onHoverState.BorderRadius = 1;
            this.statisticButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.statisticButton.onHoverState.BorderThickness = 1;
            this.statisticButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.statisticButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.statisticButton.onHoverState.IconLeftImage = null;
            this.statisticButton.onHoverState.IconRightImage = null;
            this.statisticButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.statisticButton.OnIdleState.BorderRadius = 1;
            this.statisticButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.statisticButton.OnIdleState.BorderThickness = 1;
            this.statisticButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.statisticButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.statisticButton.OnIdleState.IconLeftImage = null;
            this.statisticButton.OnIdleState.IconRightImage = null;
            this.statisticButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.statisticButton.OnPressedState.BorderRadius = 1;
            this.statisticButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.statisticButton.OnPressedState.BorderThickness = 1;
            this.statisticButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.statisticButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.statisticButton.OnPressedState.IconLeftImage = null;
            this.statisticButton.OnPressedState.IconRightImage = null;
            this.statisticButton.Size = new System.Drawing.Size(256, 45);
            this.statisticButton.TabIndex = 4;
            this.statisticButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.statisticButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.statisticButton.TextMarginLeft = 0;
            this.statisticButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.statisticButton.UseDefaultRadiusAndThickness = true;
            this.statisticButton.Click += new System.EventHandler(this.bunifuButton7_Click);
            // 
            // hoaDonBtn
            // 
            this.hoaDonBtn.AllowAnimations = true;
            this.hoaDonBtn.AllowMouseEffects = true;
            this.hoaDonBtn.AllowToggling = false;
            this.hoaDonBtn.AnimationSpeed = 200;
            this.hoaDonBtn.AutoGenerateColors = false;
            this.hoaDonBtn.AutoRoundBorders = false;
            this.hoaDonBtn.AutoSizeLeftIcon = true;
            this.hoaDonBtn.AutoSizeRightIcon = true;
            this.hoaDonBtn.BackColor = System.Drawing.Color.Transparent;
            this.hoaDonBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.hoaDonBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hoaDonBtn.BackgroundImage")));
            this.hoaDonBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.hoaDonBtn.ButtonText = "Hoá đơn";
            this.hoaDonBtn.ButtonTextMarginLeft = 0;
            this.hoaDonBtn.ColorContrastOnClick = 45;
            this.hoaDonBtn.ColorContrastOnHover = 45;
            this.hoaDonBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.hoaDonBtn.CustomizableEdges = borderEdges4;
            this.hoaDonBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hoaDonBtn.DisabledBorderColor = System.Drawing.Color.Black;
            this.hoaDonBtn.DisabledFillColor = System.Drawing.Color.Black;
            this.hoaDonBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.hoaDonBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.hoaDonBtn.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.hoaDonBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.hoaDonBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hoaDonBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hoaDonBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hoaDonBtn.IconMarginLeft = 11;
            this.hoaDonBtn.IconPadding = 10;
            this.hoaDonBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hoaDonBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hoaDonBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hoaDonBtn.IconSize = 25;
            this.hoaDonBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.hoaDonBtn.IdleBorderRadius = 1;
            this.hoaDonBtn.IdleBorderThickness = 1;
            this.hoaDonBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.hoaDonBtn.IdleIconLeftImage = null;
            this.hoaDonBtn.IdleIconRightImage = null;
            this.hoaDonBtn.IndicateFocus = false;
            this.hoaDonBtn.Location = new System.Drawing.Point(-3, 251);
            this.hoaDonBtn.Name = "hoaDonBtn";
            this.hoaDonBtn.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.hoaDonBtn.OnDisabledState.BorderRadius = 1;
            this.hoaDonBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hoaDonBtn.OnDisabledState.BorderThickness = 1;
            this.hoaDonBtn.OnDisabledState.FillColor = System.Drawing.Color.Black;
            this.hoaDonBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.hoaDonBtn.OnDisabledState.IconLeftImage = null;
            this.hoaDonBtn.OnDisabledState.IconRightImage = null;
            this.hoaDonBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hoaDonBtn.onHoverState.BorderRadius = 1;
            this.hoaDonBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hoaDonBtn.onHoverState.BorderThickness = 1;
            this.hoaDonBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hoaDonBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hoaDonBtn.onHoverState.IconLeftImage = null;
            this.hoaDonBtn.onHoverState.IconRightImage = null;
            this.hoaDonBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.hoaDonBtn.OnIdleState.BorderRadius = 1;
            this.hoaDonBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.hoaDonBtn.OnIdleState.BorderThickness = 1;
            this.hoaDonBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.hoaDonBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.hoaDonBtn.OnIdleState.IconLeftImage = null;
            this.hoaDonBtn.OnIdleState.IconRightImage = null;
            this.hoaDonBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.hoaDonBtn.OnPressedState.BorderRadius = 1;
            this.hoaDonBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hoaDonBtn.OnPressedState.BorderThickness = 1;
            this.hoaDonBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.hoaDonBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hoaDonBtn.OnPressedState.IconLeftImage = null;
            this.hoaDonBtn.OnPressedState.IconRightImage = null;
            this.hoaDonBtn.Size = new System.Drawing.Size(259, 45);
            this.hoaDonBtn.TabIndex = 2;
            this.hoaDonBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hoaDonBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hoaDonBtn.TextMarginLeft = 0;
            this.hoaDonBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.hoaDonBtn.UseDefaultRadiusAndThickness = true;
            this.hoaDonBtn.Click += new System.EventHandler(this.hoaDonBtn_Click);
            // 
            // orderBtn
            // 
            this.orderBtn.AllowAnimations = true;
            this.orderBtn.AllowMouseEffects = true;
            this.orderBtn.AllowToggling = false;
            this.orderBtn.AnimationSpeed = 200;
            this.orderBtn.AutoGenerateColors = false;
            this.orderBtn.AutoRoundBorders = false;
            this.orderBtn.AutoSizeLeftIcon = true;
            this.orderBtn.AutoSizeRightIcon = true;
            this.orderBtn.BackColor = System.Drawing.Color.Transparent;
            this.orderBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.orderBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("orderBtn.BackgroundImage")));
            this.orderBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.orderBtn.ButtonText = "Order";
            this.orderBtn.ButtonTextMarginLeft = 0;
            this.orderBtn.ColorContrastOnClick = 45;
            this.orderBtn.ColorContrastOnHover = 45;
            this.orderBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.orderBtn.CustomizableEdges = borderEdges5;
            this.orderBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.orderBtn.DisabledBorderColor = System.Drawing.Color.Black;
            this.orderBtn.DisabledFillColor = System.Drawing.Color.Black;
            this.orderBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.orderBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.orderBtn.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.orderBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.orderBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.orderBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.orderBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.orderBtn.IconMarginLeft = 11;
            this.orderBtn.IconPadding = 10;
            this.orderBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.orderBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.orderBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.orderBtn.IconSize = 25;
            this.orderBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.orderBtn.IdleBorderRadius = 1;
            this.orderBtn.IdleBorderThickness = 1;
            this.orderBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.orderBtn.IdleIconLeftImage = null;
            this.orderBtn.IdleIconRightImage = null;
            this.orderBtn.IndicateFocus = false;
            this.orderBtn.Location = new System.Drawing.Point(0, 200);
            this.orderBtn.Name = "orderBtn";
            this.orderBtn.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.orderBtn.OnDisabledState.BorderRadius = 1;
            this.orderBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.orderBtn.OnDisabledState.BorderThickness = 1;
            this.orderBtn.OnDisabledState.FillColor = System.Drawing.Color.Black;
            this.orderBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.orderBtn.OnDisabledState.IconLeftImage = null;
            this.orderBtn.OnDisabledState.IconRightImage = null;
            this.orderBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.orderBtn.onHoverState.BorderRadius = 1;
            this.orderBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.orderBtn.onHoverState.BorderThickness = 1;
            this.orderBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.orderBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.orderBtn.onHoverState.IconLeftImage = null;
            this.orderBtn.onHoverState.IconRightImage = null;
            this.orderBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.orderBtn.OnIdleState.BorderRadius = 1;
            this.orderBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.orderBtn.OnIdleState.BorderThickness = 1;
            this.orderBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.orderBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.orderBtn.OnIdleState.IconLeftImage = null;
            this.orderBtn.OnIdleState.IconRightImage = null;
            this.orderBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.orderBtn.OnPressedState.BorderRadius = 1;
            this.orderBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.orderBtn.OnPressedState.BorderThickness = 1;
            this.orderBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.orderBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.orderBtn.OnPressedState.IconLeftImage = null;
            this.orderBtn.OnPressedState.IconRightImage = null;
            this.orderBtn.Size = new System.Drawing.Size(259, 45);
            this.orderBtn.TabIndex = 2;
            this.orderBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.orderBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.orderBtn.TextMarginLeft = 0;
            this.orderBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.orderBtn.UseDefaultRadiusAndThickness = true;
            this.orderBtn.Click += new System.EventHandler(this.bunifuButton5_Click);
            // 
            // menuButton
            // 
            this.menuButton.AllowAnimations = true;
            this.menuButton.AllowMouseEffects = true;
            this.menuButton.AllowToggling = false;
            this.menuButton.AnimationSpeed = 200;
            this.menuButton.AutoGenerateColors = false;
            this.menuButton.AutoRoundBorders = false;
            this.menuButton.AutoSizeLeftIcon = true;
            this.menuButton.AutoSizeRightIcon = true;
            this.menuButton.BackColor = System.Drawing.Color.Transparent;
            this.menuButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.menuButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("menuButton.BackgroundImage")));
            this.menuButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.menuButton.ButtonText = "Menu";
            this.menuButton.ButtonTextMarginLeft = 0;
            this.menuButton.ColorContrastOnClick = 45;
            this.menuButton.ColorContrastOnHover = 45;
            this.menuButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.menuButton.CustomizableEdges = borderEdges6;
            this.menuButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.menuButton.DisabledBorderColor = System.Drawing.Color.Black;
            this.menuButton.DisabledFillColor = System.Drawing.Color.Black;
            this.menuButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.menuButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.menuButton.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.menuButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.menuButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.menuButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.menuButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.menuButton.IconMarginLeft = 11;
            this.menuButton.IconPadding = 10;
            this.menuButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.menuButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.menuButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.menuButton.IconSize = 25;
            this.menuButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.menuButton.IdleBorderRadius = 1;
            this.menuButton.IdleBorderThickness = 1;
            this.menuButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.menuButton.IdleIconLeftImage = null;
            this.menuButton.IdleIconRightImage = null;
            this.menuButton.IndicateFocus = false;
            this.menuButton.Location = new System.Drawing.Point(0, 149);
            this.menuButton.Name = "menuButton";
            this.menuButton.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.menuButton.OnDisabledState.BorderRadius = 1;
            this.menuButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.menuButton.OnDisabledState.BorderThickness = 1;
            this.menuButton.OnDisabledState.FillColor = System.Drawing.Color.Black;
            this.menuButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.menuButton.OnDisabledState.IconLeftImage = null;
            this.menuButton.OnDisabledState.IconRightImage = null;
            this.menuButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.menuButton.onHoverState.BorderRadius = 1;
            this.menuButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.menuButton.onHoverState.BorderThickness = 1;
            this.menuButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.menuButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.menuButton.onHoverState.IconLeftImage = null;
            this.menuButton.onHoverState.IconRightImage = null;
            this.menuButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.menuButton.OnIdleState.BorderRadius = 1;
            this.menuButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.menuButton.OnIdleState.BorderThickness = 1;
            this.menuButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.menuButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.menuButton.OnIdleState.IconLeftImage = null;
            this.menuButton.OnIdleState.IconRightImage = null;
            this.menuButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.menuButton.OnPressedState.BorderRadius = 1;
            this.menuButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.menuButton.OnPressedState.BorderThickness = 1;
            this.menuButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.menuButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.menuButton.OnPressedState.IconLeftImage = null;
            this.menuButton.OnPressedState.IconRightImage = null;
            this.menuButton.Size = new System.Drawing.Size(259, 45);
            this.menuButton.TabIndex = 1;
            this.menuButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.menuButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.menuButton.TextMarginLeft = 0;
            this.menuButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.menuButton.UseDefaultRadiusAndThickness = true;
            this.menuButton.Click += new System.EventHandler(this.bunifuButton4_Click);
            // 
            // overviewBtn
            // 
            this.overviewBtn.AllowAnimations = true;
            this.overviewBtn.AllowMouseEffects = true;
            this.overviewBtn.AllowToggling = false;
            this.overviewBtn.AnimationSpeed = 200;
            this.overviewBtn.AutoGenerateColors = false;
            this.overviewBtn.AutoRoundBorders = false;
            this.overviewBtn.AutoSizeLeftIcon = true;
            this.overviewBtn.AutoSizeRightIcon = true;
            this.overviewBtn.BackColor = System.Drawing.Color.Transparent;
            this.overviewBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.overviewBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("overviewBtn.BackgroundImage")));
            this.overviewBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.overviewBtn.ButtonText = "Tổng quan";
            this.overviewBtn.ButtonTextMarginLeft = 0;
            this.overviewBtn.ColorContrastOnClick = 45;
            this.overviewBtn.ColorContrastOnHover = 45;
            this.overviewBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.overviewBtn.CustomizableEdges = borderEdges7;
            this.overviewBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.overviewBtn.DisabledBorderColor = System.Drawing.Color.Black;
            this.overviewBtn.DisabledFillColor = System.Drawing.Color.Black;
            this.overviewBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.overviewBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.overviewBtn.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.overviewBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.overviewBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.overviewBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.overviewBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.overviewBtn.IconMarginLeft = 11;
            this.overviewBtn.IconPadding = 10;
            this.overviewBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.overviewBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.overviewBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.overviewBtn.IconSize = 25;
            this.overviewBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.overviewBtn.IdleBorderRadius = 1;
            this.overviewBtn.IdleBorderThickness = 1;
            this.overviewBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.overviewBtn.IdleIconLeftImage = null;
            this.overviewBtn.IdleIconRightImage = null;
            this.overviewBtn.IndicateFocus = false;
            this.overviewBtn.Location = new System.Drawing.Point(0, 98);
            this.overviewBtn.Name = "overviewBtn";
            this.overviewBtn.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.overviewBtn.OnDisabledState.BorderRadius = 1;
            this.overviewBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.overviewBtn.OnDisabledState.BorderThickness = 1;
            this.overviewBtn.OnDisabledState.FillColor = System.Drawing.Color.Black;
            this.overviewBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.overviewBtn.OnDisabledState.IconLeftImage = null;
            this.overviewBtn.OnDisabledState.IconRightImage = null;
            this.overviewBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.overviewBtn.onHoverState.BorderRadius = 1;
            this.overviewBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.overviewBtn.onHoverState.BorderThickness = 1;
            this.overviewBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.overviewBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.overviewBtn.onHoverState.IconLeftImage = null;
            this.overviewBtn.onHoverState.IconRightImage = null;
            this.overviewBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.overviewBtn.OnIdleState.BorderRadius = 1;
            this.overviewBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.overviewBtn.OnIdleState.BorderThickness = 1;
            this.overviewBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(42)))), ((int)(((byte)(33)))));
            this.overviewBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.overviewBtn.OnIdleState.IconLeftImage = null;
            this.overviewBtn.OnIdleState.IconRightImage = null;
            this.overviewBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.overviewBtn.OnPressedState.BorderRadius = 1;
            this.overviewBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.overviewBtn.OnPressedState.BorderThickness = 1;
            this.overviewBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(18)))), ((int)(((byte)(11)))));
            this.overviewBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.overviewBtn.OnPressedState.IconLeftImage = null;
            this.overviewBtn.OnPressedState.IconRightImage = null;
            this.overviewBtn.Size = new System.Drawing.Size(259, 45);
            this.overviewBtn.TabIndex = 0;
            this.overviewBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.overviewBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.overviewBtn.TextMarginLeft = 0;
            this.overviewBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.overviewBtn.UseDefaultRadiusAndThickness = true;
            this.overviewBtn.Click += new System.EventHandler(this.overviewBtn_Click_1);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::cafeManagement.Properties.Resources.logo;
            this.pictureBox1.Location = new System.Drawing.Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(267, 92);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 2;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Click += new System.EventHandler(this.pictureBox1_Click);
            // 
            // displayFormPanel
            // 
            this.displayFormPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.displayFormPanel.Location = new System.Drawing.Point(255, 0);
            this.displayFormPanel.Name = "displayFormPanel";
            this.displayFormPanel.Size = new System.Drawing.Size(868, 704);
            this.displayFormPanel.TabIndex = 2;
            // 
            // ControlForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(246)))), ((int)(((byte)(195)))));
            this.ClientSize = new System.Drawing.Size(1123, 704);
            this.Controls.Add(this.displayFormPanel);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "ControlForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Quản lí phần mềm";
            this.Load += new System.EventHandler(this.ControlForm_Load);
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.PictureBox pictureBox1;
        protected Bunifu.UI.WinForms.BunifuButton.BunifuButton overviewBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton orderBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton menuButton;
        private System.Windows.Forms.Panel displayFormPanel;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton hoaDonBtn;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton statisticButton;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton accountButton;

    }
}